# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.home_but = QtWidgets.QPushButton(self.frame)
        self.home_but.setGeometry(QtCore.QRect(320, 0, 120, 80))
        self.home_but.setObjectName("home_but")
        self.locad_but = QtWidgets.QPushButton(self.frame)
        self.locad_but.setGeometry(QtCore.QRect(440, 0, 120, 80))
        self.locad_but.setObjectName("locad_but")
        self.suggest_but = QtWidgets.QPushButton(self.frame)
        self.suggest_but.setGeometry(QtCore.QRect(560, 0, 120, 80))
        self.suggest_but.setObjectName("suggest_but")
        self.about_but = QtWidgets.QPushButton(self.frame)
        self.about_but.setGeometry(QtCore.QRect(680, 0, 120, 80))
        self.about_but.setObjectName("about_but")
        self.login_but = QtWidgets.QPushButton(self.frame)
        self.login_but.setGeometry(QtCore.QRect(200, 0, 120, 80))
        self.login_but.setObjectName("login_but")
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 90, 780, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.home_scenic_image = QtWidgets.QLabel(self.page_home)
        self.home_scenic_image.setGeometry(QtCore.QRect(0, 0, 780, 480))
        self.home_scenic_image.setObjectName("home_scenic_image")
        self.home_scenic_name = QtWidgets.QLabel(self.page_home)
        self.home_scenic_name.setGeometry(QtCore.QRect(100, 150, 60, 16))
        self.home_scenic_name.setObjectName("home_scenic_name")
        self.home_scenic_introduction = QtWidgets.QLabel(self.page_home)
        self.home_scenic_introduction.setGeometry(QtCore.QRect(450, 160, 60, 16))
        self.home_scenic_introduction.setObjectName("home_scenic_introduction")
        self.home_webEngineView = QtWebEngineWidgets.QWebEngineView(self.page_home)
        self.home_webEngineView.setGeometry(QtCore.QRect(0, 0, 780, 480))
        self.home_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.home_webEngineView.setObjectName("home_webEngineView")
        self.stackedWidget.addWidget(self.page_home)
        self.page_locad = QtWidgets.QWidget()
        self.page_locad.setObjectName("page_locad")
        self.locad_city = QtWidgets.QLabel(self.page_locad)
        self.locad_city.setGeometry(QtCore.QRect(25, 0, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.locad_city.setFont(font)
        self.locad_city.setObjectName("locad_city")
        self.label_5 = QtWidgets.QLabel(self.page_locad)
        self.label_5.setGeometry(QtCore.QRect(315, 0, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.previous_page = QtWidgets.QPushButton(self.page_locad)
        self.previous_page.setGeometry(QtCore.QRect(270, 440, 100, 32))
        self.previous_page.setObjectName("previous_page")
        self.next_page = QtWidgets.QPushButton(self.page_locad)
        self.next_page.setGeometry(QtCore.QRect(430, 440, 100, 32))
        self.next_page.setObjectName("next_page")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_locad)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 741, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.locad_scenic_image_1 = QtWidgets.QLabel(self.frame_2)
        self.locad_scenic_image_1.setGeometry(QtCore.QRect(36, 10, 290, 210))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locad_scenic_image_1.sizePolicy().hasHeightForWidth())
        self.locad_scenic_image_1.setSizePolicy(sizePolicy)
        self.locad_scenic_image_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.locad_scenic_image_1.setStyleSheet("background-color: rgb(253, 128, 30);")
        self.locad_scenic_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.locad_scenic_image_1.setObjectName("locad_scenic_image_1")
        self.locad_scenic_name_1 = QtWidgets.QLabel(self.frame_2)
        self.locad_scenic_name_1.setGeometry(QtCore.QRect(36, 230, 290, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.locad_scenic_name_1.setFont(font)
        self.locad_scenic_name_1.setObjectName("locad_scenic_name_1")
        self.locad_scenic_introduction_1 = QtWidgets.QLabel(self.frame_2)
        self.locad_scenic_introduction_1.setGeometry(QtCore.QRect(36, 280, 290, 54))
        self.locad_scenic_introduction_1.setTextFormat(QtCore.Qt.AutoText)
        self.locad_scenic_introduction_1.setScaledContents(False)
        self.locad_scenic_introduction_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.locad_scenic_introduction_1.setWordWrap(True)
        self.locad_scenic_introduction_1.setObjectName("locad_scenic_introduction_1")
        self.locad_scenic_jiage_1 = QtWidgets.QLabel(self.frame_2)
        self.locad_scenic_jiage_1.setGeometry(QtCore.QRect(36, 340, 80, 16))
        self.locad_scenic_jiage_1.setObjectName("locad_scenic_jiage_1")
        self.locad_scenic_love_1 = QtWidgets.QPushButton(self.frame_2)
        self.locad_scenic_love_1.setGeometry(QtCore.QRect(150, 330, 60, 60))
        self.locad_scenic_love_1.setObjectName("locad_scenic_love_1")
        self.locad_scenic_ding_1 = QtWidgets.QPushButton(self.frame_2)
        self.locad_scenic_ding_1.setGeometry(QtCore.QRect(270, 330, 60, 60))
        self.locad_scenic_ding_1.setObjectName("locad_scenic_ding_1")
        self.locad_scenic_fx_1 = QtWidgets.QPushButton(self.frame_2)
        self.locad_scenic_fx_1.setGeometry(QtCore.QRect(210, 330, 60, 60))
        self.locad_scenic_fx_1.setObjectName("locad_scenic_fx_1")
        self.locad_scenic_dengji_1 = QtWidgets.QLabel(self.frame_2)
        self.locad_scenic_dengji_1.setGeometry(QtCore.QRect(36, 360, 110, 16))
        self.locad_scenic_dengji_1.setObjectName("locad_scenic_dengji_1")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.locad_scenic_image_2 = QtWidgets.QLabel(self.frame_3)
        self.locad_scenic_image_2.setGeometry(QtCore.QRect(36, 10, 290, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locad_scenic_image_2.sizePolicy().hasHeightForWidth())
        self.locad_scenic_image_2.setSizePolicy(sizePolicy)
        self.locad_scenic_image_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.locad_scenic_image_2.setStyleSheet("background-color: rgb(253, 128, 30);")
        self.locad_scenic_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.locad_scenic_image_2.setObjectName("locad_scenic_image_2")
        self.locad_scenic_name_2 = QtWidgets.QLabel(self.frame_3)
        self.locad_scenic_name_2.setGeometry(QtCore.QRect(36, 230, 290, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.locad_scenic_name_2.setFont(font)
        self.locad_scenic_name_2.setObjectName("locad_scenic_name_2")
        self.locad_scenic_introduction_2 = QtWidgets.QLabel(self.frame_3)
        self.locad_scenic_introduction_2.setGeometry(QtCore.QRect(36, 280, 290, 54))
        self.locad_scenic_introduction_2.setTextFormat(QtCore.Qt.AutoText)
        self.locad_scenic_introduction_2.setScaledContents(False)
        self.locad_scenic_introduction_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.locad_scenic_introduction_2.setWordWrap(True)
        self.locad_scenic_introduction_2.setObjectName("locad_scenic_introduction_2")
        self.locad_scenic_ding_2 = QtWidgets.QPushButton(self.frame_3)
        self.locad_scenic_ding_2.setGeometry(QtCore.QRect(270, 330, 60, 60))
        self.locad_scenic_ding_2.setObjectName("locad_scenic_ding_2")
        self.locad_scenic_love_2 = QtWidgets.QPushButton(self.frame_3)
        self.locad_scenic_love_2.setGeometry(QtCore.QRect(150, 330, 60, 60))
        self.locad_scenic_love_2.setObjectName("locad_scenic_love_2")
        self.locad_scenic_jiage_2 = QtWidgets.QLabel(self.frame_3)
        self.locad_scenic_jiage_2.setGeometry(QtCore.QRect(36, 340, 80, 16))
        self.locad_scenic_jiage_2.setObjectName("locad_scenic_jiage_2")
        self.locad_scenic_fx_2 = QtWidgets.QPushButton(self.frame_3)
        self.locad_scenic_fx_2.setGeometry(QtCore.QRect(210, 330, 60, 60))
        self.locad_scenic_fx_2.setObjectName("locad_scenic_fx_2")
        self.locad_scenic_dengji_2 = QtWidgets.QLabel(self.frame_3)
        self.locad_scenic_dengji_2.setGeometry(QtCore.QRect(36, 360, 110, 16))
        self.locad_scenic_dengji_2.setObjectName("locad_scenic_dengji_2")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.ld_fenlei = QtWidgets.QComboBox(self.page_locad)
        self.ld_fenlei.setGeometry(QtCore.QRect(580, 10, 80, 26))
        self.ld_fenlei.setObjectName("ld_fenlei")
        self.ld_city = QtWidgets.QComboBox(self.page_locad)
        self.ld_city.setGeometry(QtCore.QRect(660, 10, 80, 26))
        self.ld_city.setObjectName("ld_city")
        self.stackedWidget.addWidget(self.page_locad)
        self.page_suggest = QtWidgets.QWidget()
        self.page_suggest.setObjectName("page_suggest")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.page_suggest)
        self.horizontalFrame_3.setGeometry(QtCore.QRect(140, 10, 500, 45))
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ss_comboBox = QtWidgets.QComboBox(self.horizontalFrame_3)
        self.ss_comboBox.setMinimumSize(QtCore.QSize(0, 26))
        self.ss_comboBox.setObjectName("ss_comboBox")
        self.ss_comboBox.addItem("")
        self.ss_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.ss_comboBox)
        self.ss_lineEdit = QtWidgets.QLineEdit(self.horizontalFrame_3)
        self.ss_lineEdit.setObjectName("ss_lineEdit")
        self.horizontalLayout_3.addWidget(self.ss_lineEdit)
        self.ss_ssbutton = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.ss_ssbutton.setObjectName("ss_ssbutton")
        self.horizontalLayout_3.addWidget(self.ss_ssbutton)
        self.ss_listWidget = QtWidgets.QListWidget(self.page_suggest)
        self.ss_listWidget.setGeometry(QtCore.QRect(10, 60, 760, 460))
        self.ss_listWidget.setObjectName("ss_listWidget")
        self.stackedWidget.addWidget(self.page_suggest)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.my = QtWidgets.QTabWidget(self.page_about)
        self.my.setGeometry(QtCore.QRect(10, 10, 760, 460))
        self.my.setUsesScrollButtons(False)
        self.my.setDocumentMode(True)
        self.my.setTabsClosable(False)
        self.my.setMovable(False)
        self.my.setTabBarAutoHide(False)
        self.my.setObjectName("my")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 760, 430))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.user_love_listWidget = QtWidgets.QListWidget(self.tab_6)
        self.user_love_listWidget.setGeometry(QtCore.QRect(10, 10, 740, 400))
        self.user_love_listWidget.setObjectName("user_love_listWidget")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.my.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 760, 430))
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.my.addTab(self.tab_4, "")
        self.stackedWidget.addWidget(self.page_about)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.my.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home_but.setText(_translate("MainWindow", "主页"))
        self.locad_but.setText(_translate("MainWindow", "本地"))
        self.suggest_but.setText(_translate("MainWindow", "搜索"))
        self.about_but.setText(_translate("MainWindow", "我的"))
        self.login_but.setText(_translate("MainWindow", "登陆"))
        self.home_scenic_image.setText(_translate("MainWindow", "TextLabel"))
        self.home_scenic_name.setText(_translate("MainWindow", "清明上河园"))
        self.home_scenic_introduction.setText(_translate("MainWindow", "TextLabel"))
        self.locad_city.setText(_translate("MainWindow", "定位：开封"))
        self.label_5.setText(_translate("MainWindow", "本地热门景区推荐"))
        self.previous_page.setText(_translate("MainWindow", "上一页"))
        self.next_page.setText(_translate("MainWindow", "下一页"))
        self.locad_scenic_image_1.setText(_translate("MainWindow", "image"))
        self.locad_scenic_name_1.setText(_translate("MainWindow", "景点名称"))
        self.locad_scenic_introduction_1.setText(_translate("MainWindow", "景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍"))
        self.locad_scenic_jiage_1.setText(_translate("MainWindow", "价格：000"))
        self.locad_scenic_love_1.setText(_translate("MainWindow", "收藏"))
        self.locad_scenic_ding_1.setText(_translate("MainWindow", "预定"))
        self.locad_scenic_fx_1.setText(_translate("MainWindow", "分享"))
        self.locad_scenic_dengji_1.setText(_translate("MainWindow", "等级：5A"))
        self.locad_scenic_image_2.setText(_translate("MainWindow", "image"))
        self.locad_scenic_name_2.setText(_translate("MainWindow", "景点名称"))
        self.locad_scenic_introduction_2.setText(_translate("MainWindow", "景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍景点介绍"))
        self.locad_scenic_ding_2.setText(_translate("MainWindow", "预定"))
        self.locad_scenic_love_2.setText(_translate("MainWindow", "收藏"))
        self.locad_scenic_jiage_2.setText(_translate("MainWindow", "价格：000"))
        self.locad_scenic_fx_2.setText(_translate("MainWindow", "分享"))
        self.locad_scenic_dengji_2.setText(_translate("MainWindow", "等级：5A"))
        self.ss_comboBox.setItemText(0, _translate("MainWindow", "城市"))
        self.ss_comboBox.setItemText(1, _translate("MainWindow", "景点"))
        self.ss_ssbutton.setText(_translate("MainWindow", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "个人信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "我的收藏"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "我的订单"))
        self.my.setTabText(self.my.indexOf(self.tab_3), _translate("MainWindow", "我的信息"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "用户管理"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "订单管理"))
        self.my.setTabText(self.my.indexOf(self.tab_4), _translate("MainWindow", "管理员管理"))

from PyQt5 import QtWebEngineWidgets
